import * as fs from "fs";

import * as path from "path";
import * as yaml from "js-yaml";
import chalk from "chalk";
import { Platform } from "@coolcinema/platform";

export const initCommand = async () => {
  const cwd = process.cwd();
  const dirName = path.basename(cwd);
  const manifestPath = path.join(cwd, "coolcinema.yaml");

  if (fs.existsSync(manifestPath)) {
    console.error(chalk.red("❌ coolcinema.yaml already exists."));
    process.exit(1);
  }

  // 1. Базовая структура (Metadata)
  const manifest: any = {
    version: "1.0.0",
    metadata: {
      name: toPascalCase(dirName),
      slug: dirName,
      description: "Service description placeholder",
      language: "typescript",
    },
    interfaces: {},
  };

  // 2. Добавляем шаблоны от всех модулей
  // Platform.getAll() вернет [GrpcModule]
  for (const module of Platform.getAll()) {
    // В interfaces добавляется секция 'grpc': { ...template }
    manifest.interfaces[module.id] = module.getTemplate();
  }

  // 3. Сохраняем с комментариями
  const yamlContent = yaml.dump(manifest);

  // Добавляем подсказку в начало файла
  const fileContent = `# CoolCinema Service Manifest
# Generated by CLI. Please fill in the details.

${yamlContent}`;

  fs.writeFileSync(manifestPath, fileContent);

  console.log(
    chalk.green(`
✅ Created coolcinema.yaml`),
  );
  console.log(
    chalk.white(
      `Please open it and configure your interfaces (paths to proto, etc).`,
    ),
  );
};

// Helper
function toPascalCase(str: string) {
  return str
    .replace(/(?:^\w|[A-Z]|\b\w)/g, (word) => word.toUpperCase())
    .replace(/[\s\-_]+/g, "");
}
