import * as fs from "fs";
import * as path from "path";
import { glob } from "glob";
import { Platform, CompileContext } from "@coolcinema/platform";

const servicesDir = path.join(__dirname, "../services");
const srcDir = path.join(__dirname, "../src"); // Или генерируем прямо в src, если tsc настроен на него

// Создаем пустую папку src (или очищаем)
if (fs.existsSync(srcDir)) fs.rmSync(srcDir, { recursive: true, force: true });
fs.mkdirSync(srcDir, { recursive: true });

async function build() {
  console.log("🚀 Starting Catalog Build...");

  // 1. Находим все манифесты
  const manifestFiles = await glob(path.join(servicesDir, "*/manifest.json"));
  const exports: string[] = [];

  for (const file of manifestFiles) {
    const serviceDir = path.dirname(file); // .../services/identity
    const manifest = JSON.parse(fs.readFileSync(file, "utf8"));
    const serviceName = manifest.metadata.name; // "Identity"
    const serviceSlug = manifest.metadata.slug; // "identity-service"

    console.log(`📦 Compiling service: ${serviceName}...`);

    // Подпапка для этого сервиса в src (чтобы не было коллизий)
    // src/services/identity
    const serviceOutDir = path.join(srcDir, "services", serviceSlug);
    fs.mkdirSync(serviceOutDir, { recursive: true });

    // Контекст для модуля
    const ctx: CompileContext = {
      serviceName,
      serviceDir,
      outDir: serviceOutDir, // Куда класть .ts файлы
    };

    // 2. Проходим по интерфейсам (grpc, http...)
    for (const [moduleId, config] of Object.entries(manifest.interfaces)) {
      const module = Platform.get(moduleId);
      if (!module) continue;

      console.log(`   - Module: ${moduleId}`);

      // Запускаем компиляцию (например, buf generate)
      // Модуль сам создаст файлы внутри ctx.outDir
      const generatedFiles = await module.onCompile(ctx, config);

      // Логируем
      generatedFiles.forEach((f) => console.log(`     -> Generated: ${f}`));
    }

    // 3. Добавляем экспорт в index.ts
    // Мы экспортируем всё из папки сервиса
    // export * as Identity from './services/identity';
    exports.push(
      `export * as ${serviceName} from './services/${serviceSlug}';`,
    );

    // Также экспортируем конфиг (манифест), чтобы API мог его читать в рантайме?
    // Нет, API читает типы. А рантайм конфиг (url) нужен.
    // Давайте сгенерируем метаданные в код.
    const metaCode = `export const ${serviceName}Meta = ${JSON.stringify(manifest.metadata)};`;
    fs.writeFileSync(path.join(serviceOutDir, "meta.ts"), metaCode);
    exports.push(
      `export { ${serviceName}Meta } from './services/${serviceSlug}/meta';`,
    );
  }

  // 4. Создаем index.ts
  const indexContent = [
    "/**",
    " * AUTO-GENERATED BY COOLCINEMA CATALOG COMPILER",
    " * DO NOT EDIT",
    " */",
    ...exports,
  ].join("\n");

  fs.writeFileSync(path.join(srcDir, "index.ts"), indexContent);

  console.log("✅ Catalog Build Complete.");
}

build().catch((e) => {
  console.error(e);
  process.exit(1);
});
